### ISSUE TITLE
can't load past the server trying to open

### ISSUE THREAD

**Issue by Dahjro** [Solarint/SAIN#103]
BepinEx/plugins: 
CWX
Waypoints
Hitmarker
Kiki-AllTheBoss
Kiki-DegredationRemover
EFTApi
GamePanelHud
Kobrakon-adrenaline
Kobrakon-TAB
SAIN
SPT
LotsOfLoot

user/mods:
WeightTweaker
SPTQuestingBots
DoorBreacher
BetterBackpacks
UltimateClearNVGs
ClearVision
Priscilu
openextracts
NLE
ServerValueModifier
NoDiscardLimit
SensibleUniversalWeaponMods
AmmoStats
SAINServerMod
Waypoints

`TypeError: Cannot read properties of undefined (reading 'pmcType')
TypeError: Cannot read properties of undefined (reading 'pmcType')
    at SAIN.postDBLoad (C:\Users\----\Desktop\SPT\user\mods\zSolarint-SAIN-ServerMod\src\mod.js:19:48)
    at PostDBModLoader.executeMods (C:\snapshot\project\obj\loaders\PostDBModLoader.js)
    at PostDBModLoader.onLoad (C:\snapshot\project\obj\loaders\PostDBModLoader.js)
    at App.load (C:\snapshot\project\obj\utils\App.js)
TypeError: Cannot read properties of undefined (reading 'pmcType')
TypeError: Cannot read properties of undefined (reading 'pmcType')
    at SAIN.postDBLoad (C:\Users\----\Desktop\SPT\user\mods\zSolarint-SAIN-ServerMod\src\mod.js:19:48)
    at PostDBModLoader.executeMods (C:\snapshot\project\obj\loaders\PostDBModLoader.js)
    at PostDBModLoader.onLoad (C:\snapshot\project\obj\loaders\PostDBModLoader.js)
    at App.load (C:\snapshot\project\obj\utils\App.js)
`

**Comment by MONKYBOMBER** [comment]
same issue

**Comment by Dahjro** [comment]
> same issue

i think my spt was outdated, it was on 3.6.1

**Comment by Nick3030303** [comment]
Make sure all the file versions are right!

**Comment by Solarint** [comment]
sain will only work on the version of spt it was made for.
