### ISSUE TITLE
[FIXED: REMOVE BETTER SPAWNS PLUS] New in-game SAIN errors caused by questing bots?

### ISSUE THREAD

**Issue by Lodgercat** [Solarint/SAIN#134]
The console comes up with this error when in-raid:

> TypeError: Cannot read properties of undefined (reading 'experience')
>     at BotGenerator.generateBot (C:\snapshot\src\generators\BotGenerator.ts:147:29)
>     at BotGenerator.prepareAndGenerateBot (C:\snapshot\src\generators\BotGenerator.ts:116:20)
>     at BotController.generateBotsFirstTime (C:\snapshot\src\controllers\BotController.ts:256:54)
>     at BotController.generate (C:\snapshot\src\controllers\BotController.ts:188:25)
>     at QuestingBots.generateBots (E:\Games\SPT\SPT 3.8.3\user\mods\DanW-SPTQuestingBots\src\mod.ts:532:41)
>     at Object.action (E:\Games\SPT\SPT 3.8.3\user\mods\DanW-SPTQuestingBots\src\mod.ts:187:39)
>     at DynamicRouterMod.handleDynamic (C:\snapshot\src\di\Router.ts:65:59)
>     at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:74:63)
>     at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:46:18)
>     at AkiHttpListener.getResponse (C:\snapshot\src\servers\http\AkiHttpListener.ts:150:38)

This is in addition to SAIN being cancelled for each bot due to "not having a base brain. SAIN server mod is either missing or another mod is overwriting it. Destroying SAIN for this bot"

Might not be relevant but am also getting this error in the console too:

> Error: Items must not be empty
>     at WeightedRandomHelper.weightedRandom (C:\snapshot\src\helpers\WeightedRandomHelper.ts:54:19)
>     at WeightedRandomHelper.getWeightedValue (C:\snapshot\src\helpers\WeightedRandomHelper.ts:31:33)
>     at BotWeaponGenerator.getWeightedCompatibleAmmo (C:\snapshot\src\generators\BotWeaponGenerator.ts:603:60)
>     at BotWeaponGenerator.generateWeaponByTpl (C:\snapshot\src\generators\BotWeaponGenerator.ts:150:30)
>     at BotWeaponGenerator.generateRandomWeapon (C:\snapshot\src\generators\BotWeaponGenerator.ts:84:21)
>     at BotInventoryGenerator.addWeaponAndMagazinesToInventory (C:\snapshot\src\generators\BotInventoryGenerator.ts:543:57)
>     at BotInventoryGenerator.generateAndAddWeaponsToBot (C:\snapshot\src\generators\BotInventoryGenerator.ts:484:22)
>     at BotInventoryGenerator.generateInventory (C:\snapshot\src\generators\BotInventoryGenerator.ts:80:14)
>     at BotGenerator.generateBot (C:\snapshot\src\generators\BotGenerator.ts:195:52)
>     at BotGenerator.prepareAndGenerateBot (C:\snapshot\src\generators\BotGenerator.ts:116:20)
> Error: Items must not be empty
> Error: Items must not be empty
>     at WeightedRandomHelper.weightedRandom (C:\snapshot\src\helpers\WeightedRandomHelper.ts:54:19)
>     at WeightedRandomHelper.getWeightedValue (C:\snapshot\src\helpers\WeightedRandomHelper.ts:31:33)
>     at BotWeaponGenerator.getWeightedCompatibleAmmo (C:\snapshot\src\generators\BotWeaponGenerator.ts:603:60)
>     at BotWeaponGenerator.generateWeaponByTpl (C:\snapshot\src\generators\BotWeaponGenerator.ts:150:30)
>     at BotWeaponGenerator.generateRandomWeapon (C:\snapshot\src\generators\BotWeaponGenerator.ts:84:21)
>     at BotInventoryGenerator.addWeaponAndMagazinesToInventory (C:\snapshot\src\generators\BotInventoryGenerator.ts:543:57)
>     at BotInventoryGenerator.generateAndAddWeaponsToBot (C:\snapshot\src\generators\BotInventoryGenerator.ts:484:22)
>     at BotInventoryGenerator.generateInventory (C:\snapshot\src\generators\BotInventoryGenerator.ts:80:14)
>     at BotGenerator.generateBot (C:\snapshot\src\generators\BotGenerator.ts:195:52)
>     at BotGenerator.prepareAndGenerateBot (C:\snapshot\src\generators\BotGenerator.ts:116:20)

**Comment by qxq18080** [comment]
I also encountered this error.
"not having a base brain. SAIN server mod is either missing or another mod is overwriting it. Destroying SAIN for this bot"

**Comment by iSzane** [comment]
For us its the same. SAIN 2.3.3 is currently unplayable :/
![image](https://github.com/Solarint/SAIN/assets/170347772/713b7956-8bbb-41fc-bb7b-62e31a2185c6)

**Comment by PinkPlushie** [comment]
It is not caused by Questing Bots (or at least not *only* caused by QB). I do not use QB and I have this exact problem. We use Fika. Fresh install of SAIN 2.3.3 server and client, all clients installed correctly. We temporarily downgraded.

**Comment by Littlelucy99** [comment]
We also have indeed the same problem.. It might be a problem with Fika.. first i thought it was the fault of QB.. which was not the issue. For me its BOSS..
![2024-06-02 21-24 _-21 2, 25 1, -22 5_0 4, -0 3, 0 2, 0 8_18 90 (0)](https://github.com/Solarint/SAIN/assets/85967105/3025e654-16e2-496b-b379-7baba17ef2d0)

**Comment by PinkPlushie** [comment]
The error messages I have also reference bosses specifically. Exact same error messages you're seeing. I can confirm it is *not* caused by Algorithmic Level Progression, which is the only other mod affecting bots that I updated alongside SAIN. It's not SWAG+Donuts either as far as I can tell.

**Comment by Solarint** [comment]
As the error says, its an issue where sain's server mod is being overwritten. Make sure its installed and being loaded last, currently I've had people say its caused by Better Spawns Plus mostly.

**Comment by Solarint** [comment]
As for the bot gen error, it has nothing to do with sain. Sain doesn't modify bot generation at all, only the brain they are set to in the server mod, which is vanilla SPT code.

**Comment by Littlelucy99** [comment]
As you say its most the mod "Better Spawn Plus" after removing it it was fixed no more error on going. Ty for advise.

**Comment by Lodgercat** [comment]
[order.json](https://github.com/user-attachments/files/15537664/order.json)

Changing the load order fixed the console errors and I can confirm removing better spawns plus fixed the in game notifications. Thanks everyone :)
