### ISSUE TITLE
SAIN Crashes on FIKA

### ISSUE THREAD

**Issue by lamduong33** [Solarint/SAIN#165]
Hi, I'm running a FIKA server. Sorry but I don't know where else to go for this issue. I'm running a Fika server on Linux. Decided to update everything to 3.9.0 and received this error instead. I have copied all of the Bepinex and user folders from SAIN, BigBrain, and WayPoints.

Server Mods:
- SAIN v3.0.1 for SPTv3.9.0
- BigBrain v1.0.0
- WayPoints v1.5.0
- LiveFleaPrices v1.2.0
- Fika 2.2.2

 Whenever the server starts, here is the log:

`
┌─────────────────────────────────────────┐
│ SPT 3.9.0                               │
│ https://discord.sp-tarkov.com           │
│                                         │
│ This work is free of charge             │
│ If you paid money, you were scammed     │
│ Commercial use is prohibited            │
└─────────────────────────────────────────┘
ModLoader: loading: 3 server mods...
Mod: LiveFleaPrices version: 1.2.0 by: DrakiaXYZ loaded
Mod: server version: 2.2.2 by: Fika loaded
Mod: SAIN version: 3.0.1 by: Solarint loaded
ModLoader: Error when loading async mod: Cannot inject the dependency "overrider" at position #1 of "Fika" constructor. Reason:
    Cannot inject the dependency "overrides" at position #0 of "Overrider" constructor. Reason:
        Cannot inject the dependency "locationController" at position #0 of "LocationCallbacksOverride" constructor. Reason:
            Cannot inject the dependency "locationGenerator" at position #4 of "LocationController" constructor. Reason:
                Config: spt-location is undefined. Ensure you have not broken it via editing
Error: Cannot inject the dependency "overrider" at position #1 of "Fika" constructor. Reason:
    Cannot inject the dependency "overrides" at position #0 of "Overrider" constructor. Reason:
        Cannot inject the dependency "locationController" at position #0 of "LocationCallbacksOverride" constructor. Reason:
            Cannot inject the dependency "locationGenerator" at position #4 of "LocationController" constructor. Reason:
                Config: spt-location is undefined. Ensure you have not broken it via editing
    at /snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:324:23
    at Array.map (<anonymous>)
    at /snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:295:38
    at InternalDependencyContainer.construct (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:297:11)
    at InternalDependencyContainer.resolveRegistration (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:166:51)
    at InternalDependencyContainer.resolve (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:109:33)
    at Mod.preSptLoadAsync (/opt/server/user/mods/fika-server/src/mod.ts:13:25)
    at PreSptModLoader.executeModsAsync (/snapshot/src/loaders/PreSptModLoader.ts:401:68)
    at PreSptModLoader.load (/snapshot/src/loaders/PreSptModLoader.ts:59:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
The application had a critical error and failed to run
Exception produced: Error

Stacktrace:
Error: Cannot inject the dependency "httpServer" at position #5 of "App" constructor. Reason:
    Cannot inject the dependency "httpListeners" at position #4 of "HttpServer" constructor. Reason:
        Cannot inject the dependency "httpRouter" at position #0 of "SptHttpListener" constructor. Reason:
            Cannot inject the dependency "staticRouters" at position #0 of "HttpRouter" constructor. Reason:
                Cannot inject the dependency "gameCallbacks" at position #0 of "GameStaticRouter" constructor. Reason:
                    Cannot inject the dependency "gameController" at position #3 of "GameCallbacks" constructor. Reason:
                        Cannot inject the dependency "customLocationWaveService" at position #11 of "GameController" constructor. Reason:
                            Config: spt-location is undefined. Ensure you have not broken it via editing
    at /snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:324:23
    at Array.map (<anonymous>)
    at /snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:295:38
    at InternalDependencyContainer.construct (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:297:11)
    at InternalDependencyContainer.resolveRegistration (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:166:51)
    at InternalDependencyContainer.resolve (/snapshot/project/node_modules/tsyringe/dist/cjs/dependency-container.js:109:33)
    at Program.start (/snapshot/src/Program.ts:32:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:64:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1984:13)
`

**Comment by lamduong33** [comment]
This seems like a project fika issue. Sorry for posting this here.
